volumes:
  db_data:
services:
  db:
    image: mysql:9.1.0
    environment:
      - MYSQL_DATABASE=orda
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=orda
      - MYSQL_PASSWORD=orda
    command:
      - --performance_schema=0
      - --innodb_use_native_aio=0
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
  adminer:
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - db
