volumes:
  db_data:
  metabase-data:
  sqlpad-data:
services:
  db:
    image: mysql:9.1.0
    environment:
      - MYSQL_DATABASE=orda
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=orda
      - MYSQL_PASSWORD=orda
    command:
      - --performance_schema=0
      - --innodb_use_native_aio=0
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
  adminer:
    image: adminer:latest
    ports:
      - 8081:8080
    depends_on:
      - db
  metabase:
    ## https://www.metabase.com/docs/latest/installation-and-operation/running-metabase-on-docker
    image: metabase/metabase:latest
    container_name: metabase
    volumes:
      - metabase-data:/metabase-data
    ports:
      - 8082:3000
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    depends_on:
      - db
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  # sqlpad:
  #   image: sqlpad/sqlpad:5
  #   ports:
  #     - "8083:3000"
  #   environment:
  #     SQLPAD_ADMIN: admin
  #     SQLPAD_ADMIN_PASSWORD: admin
  #     SQLPAD_APP_LOG_LEVEL: info
  #     SQLPAD_WEB_LOG_LEVEL: warn
  #     SQLPAD_CONNECTIONS__mysql__name: orda
  #     SQLPAD_CONNECTIONS__mysql__driver: mysql2
  #     SQLPAD_CONNECTIONS__mysql__host: db
  #     SQLPAD_CONNECTIONS__mysql__database: orda
  #     SQLPAD_CONNECTIONS__mysql__username: orda
  #     SQLPAD_CONNECTIONS__mysql__password: orda
  #   volumes:
  #     - sqlpad-data:/var/lib/sqlpad
