version: "3.9"
services:
  orda:
    image: scharphio/orda/orda:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    volumes:
      - .env:/.env
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  db_data:
