volumes:
  db_prod:
networks:
  web:
    external: true
  internal_prod:
    external: false
services:
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=orda
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=orda
      - MYSQL_PASSWORD=orda
    command:
      - --performance_schema=0
      - --innodb_use_native_aio=0
    volumes:
      - db_prod:/var/lib/mysql
      #- ./mysql/init:/docker-entrypoint-initdb.d/:ro
    networks:
      - internal_prod
    labels:
      - traefik.enable=false
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
  adminer:
    image: adminer
    networks:
      - internal_prod
    labels:
      - traefik.enable=false
    ports:
      - 8081:8080
