volumes:
  db_prod:
networks:
  web:
    external: true
  internal_prod:
    external: false
services:
  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.orda.rule=Host(`orda.schartis.at`)"
      - "traefik.http.routers.orda.tls=true"
    networks:
      - web
  orda:
    image: scharphio/orda:v0.1.3
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=orda
      - DB_PASSWORD=orda
      - DB_NAME=orda
      - PORT=80
      - TZ=Europe/Vienna
    labels:
      - "traefik.http.routers.ordadev.rule=Host(`orda-dev.schartis.at`)"
      - "traefik.http.routers.ordadev.tls=true"
      - "traefik.docker.network=web"
    networks:
      - web
      - internal_prod
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=orda
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=orda
      - MYSQL_PASSWORD=orda
    command:
      - --performance_schema=0
      - --innodb_use_native_aio=0
    volumes:
      - db_prod:/var/lib/mysql
      #- ./mysql/init:/docker-entrypoint-initdb.d/:ro
    networks:
      - internal_prod
    labels:
      - traefik.enable=false
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
