services:
  traefik:
    image: traefik:v3.3.4
    container_name: traefik
    ports:
      - "443:443"
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-certs:/letsencrypt"
      - "./traefik.yaml:/traefik.yaml:ro" # Traefik config file
      - ./log:/var/log/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`proxy.schartis.at`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=philipp:$$2y$$05$$8OR3lTI6U8EeMVIUkCpsMeGQqVsEbOruOS245PtDPaBbUd5USpiQu"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
    networks:
      - proxy

volumes:
  traefik-certs:
    name: traefik-certs

networks:
  proxy:
    external: true
