volumes:
  db_prod:
networks:
  proxy:
    external: true
  internal:
    external: false
services:
  orda:
    image: scharphio/orda:v0.2.0
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_ENV=production
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=orda
      - DATABASE_PASSWORD=orda
      - DATABASE_NAME=orda
      - SERVER_PORT=80
      - SERVER_HOST=localhost
      - SERVER_TZ=Europe/Vienna
      - SERVER_ENFORCERFILE=/etc/orda/rbac_model.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ordav2.rule=Host(`orda.schartis.at`)"
      - "traefik.http.routers.ordav2.tls=true"
      - "traefik.http.routers.ordav2.tls.certresolver=letsencrypt"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - internal
    volumes:
      - ./config:/etc/orda
    restart: unless-stopped
  db:
    image: mysql:8.3
    environment:
      - MYSQL_DATABASE=orda
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=orda
      - MYSQL_PASSWORD=orda
    command:
      - --performance_schema=0
      - --innodb_use_native_aio=0
    volumes:
      - db_prod:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d/:ro
    networks:
      - internal
    labels:
      - traefik.enable=false
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "1.0"
          memory: 600M
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
