volumes:
  metabase_data:
networks:
  proxy:
    external: true
  internal_v2:
    external: true
services:
  adminer:
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=nette
      - ADMINER_DEFAULT_DB_NAME=orda
      - ADMINER_DEFAULT_DB_HOST=db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.schartis.at`)"
      - "traefik.http.routers.adminer.tls=true"
      - "traefik.http.routers.adminer.tls.certresolver=letsencrypt"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - internal_v2
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - metabase_data:/metabase-data
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    networks:
      - proxy
      - internal_v2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metabase.rule=Host(`metabase.schartis.at`)"
      - "traefik.http.routers.metabase.tls=true"
      - "traefik.http.routers.metabase.tls.certresolver=letsencrypt"
      - "traefik.docker.network=proxy"
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
