CREATE DATABASE IF NOT EXISTS casbin;
CREATE DATABASE IF NOT EXISTS fiber;
CREATE DATABASE IF NOT EXISTS metabase;

CREATE USER 'metabase' IDENTIFIED BY 'metabase';

GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `casbin`.* TO 'orda'@'%';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `fiber`.* TO 'orda'@'%';
GRANT ALL ON `metabase`.* TO 'metabase'@'%';

FLUSH PRIVILEGES;
