name: Makefile CI

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"

env:
  IMAGE: orda

jobs:
  # This workflow contains multiple jobs
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v5
        if: github.ref != 'refs/heads/master'
        with:
          context: .
          file: ./ci/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE }}:${{ github.ref_name }}
          build-args: |
            NODE_VERSION=${{ matrix.node-version }}
            BUILD=${{ github.ref_name }}
      - name: Build and push
        uses: docker/build-push-action@v5
        if: github.ref == 'refs/heads/master'
        with:
          context: .
          file: ./ci/Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE }}:v0.0.1-master.${{ github.sha }}
          build-args: |
            NODE_VERSION=${{ matrix.node-version }}
            BUILD=v0.0.1-master.${{ github.sha }}

