name: Makefile CI

on:
  push:
    tags:
      - 'v*'

jobs:
  # This workflow contains multiple jobs
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    strategy:
      matrix:
        node-version: [18.x]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      # install applicaion dependencies
      - name: Build
        run: make build-local 
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/orda*
          file_glob: true
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}

